### ISSUE TITLE
Issue when trying to use importer via Blender's Python console

### ISSUE THREAD

**Issue by GriboNexGen** [Arbos/nwn2mdk#8]
I'm trying the following command:  bpy.ops.import_scene.nwn2mdk(filepath="d:\temp\p_hhm\p_hhm_kemo_chair_1drow1.gr2")
Getting this error:

Error: Python: Traceback (most recent call last):
  File "C:\Users\gribo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\nwn2mdk\__init__.py", line 178, in execute
    with open(os.path.join(working_dir, "log.txt"), "w") as log:
OSError: [Errno 22] Invalid argument: 'd:\temp\\p_hhm\\log.txt'
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Users\gribo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\nwn2mdk\__init__.py", line 178, in execute
    with open(os.path.join(working_dir, "log.txt"), "w") as log:
OSError: [Errno 22] Invalid argument: 'd:\temp\\p_hhm\\log.txt'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\gribo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\nwn2mdk\__init__.py", line 178, in execute
    with open(os.path.join(working_dir, "log.txt"), "w") as log:
OSError: [Errno 22] Invalid argument: 'd:\temp\\p_hhm\\log.txt'
Location: C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py:113

**Comment by GriboNexGen** [comment]
The log file reported is 'd:\temp\\\p_hhm\\\log.txt'
